# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chess.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chess.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hess.proto\x12\nchess_grpc\"4\n\x0bMoveRequest\x12\x13\n\x0b\x62oard_state\x18\x01 \x01(\t\x12\x10\n\x08is_white\x18\x02 \x01(\x08\"#\n\x0cMoveResponse\x12\x13\n\x0b\x62oard_state\x18\x01 \x01(\t2H\n\x05\x43hess\x12?\n\x08MakeMove\x12\x17.chess_grpc.MoveRequest\x1a\x18.chess_grpc.MoveResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chess_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVEREQUEST']._serialized_start=27
  _globals['_MOVEREQUEST']._serialized_end=79
  _globals['_MOVERESPONSE']._serialized_start=81
  _globals['_MOVERESPONSE']._serialized_end=116
  _globals['_CHESS']._serialized_start=118
  _globals['_CHESS']._serialized_end=190
# @@protoc_insertion_point(module_scope)
